# Use an OpenJDK base image
FROM openjdk:17-jdk-alpine

# Set working directory
WORKDIR /app

# Copy pom.xml for dependency analysis
COPY pom.xml ./

# Cache Maven dependencies
RUN apt-get update && \
    apt-get install -y wget && \
    wget -q https://dlcdn.apache.org/maven/apache-maven-3.9.7-bin.tar.gz && \
    tar -xzf apache-maven-3.9.7-bin.tar.gz -C /usr/local/ && \
    rm apache-maven-3.9.7-bin.tar.gz && \
    echo "export PATH=/usr/local/apache-maven-3.9.7/bin:\$PATH" >> ~/.bashrc

# Download and install Appium
RUN wget https://github.com/appium/appium/archive/refs/heads/main.zip && \
    unzip main.zip -d appium && \
    mv appium-main appium && \
    rm main.zip && \
    cd appium/build/lib && \
    ./install.sh

# Copy project code
COPY src src
COPY pom.xml ./

# Install dependencies
RUN mvn clean install

# Expose Appium port
EXPOSE 4723

# Command to run
CMD ["appium", "--log-level", "debug"]
